name: Allure Report CI/CD

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

##setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

## buat gradlew permission
      - name: Give permission to gradlew
        run: chmod +x gradlew

      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y unzip
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.zip
          unzip allure.zip
          sudo mv allure-2.25.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

## permission untuk menjalankan script merge allure report
      - name: Give permission to script
        run: chmod +x merge-allure.sh

## menjalankan script untuk menggabungkan laporan Allure
      - name: Run Allure tests and generate report
        run: ./merge-allure.sh

## deploy laporan Allure ke GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./merged-allure-report
          publish_branch: gh-pages
          force_orphan: true